apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod-file
spec:
  containers:
    - name: test-container
      image: nginx
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: sensitive
              key: username.txt
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sensitive
              key: password.txt

