apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: overfishing
spec:
  selector:
    app: overfishing
    type: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http

