apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: overfishing
spec:
  selector:
    app: overfishing
    type: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
