apiVersion: apps/v1
kind: Deployment
metadata:
  name: overfishing-backend
  labels:
    app: overfishing
spec:
  selector:
    matchLabels:
      app: overfishing
      type: backend
  template:
    metadata:
      name: overfishing-be
      labels:
        app: overfishing
        type: backend
    spec:
      containers:
        - name: backend
          image: overfishing-be
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: REDIS_HOST
              value: backend-service
            - name: REDIS_PORT
              value: "6379"
