apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: overfishing
spec:
  selector:
    type: redis
    app: overfishing
  ports:
    - protocol: TCP
      port: 6379
      targetPort: redis-port
