apiVersion: v1
kind: Pod
metadata:
  name: dapi-volume
  labels:
    zone: zone-1
    cluster: cluster-1
  annotations:
    build: two
    builder: john-doe
spec:
  containers:
    - name: client-container
      image: nginx
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
          readOnly: false
  volumes:
    - name: podinfo
      downwardAPI:
          items:
            - path: "labels"
              fieldRef:
                fieldPath: metadata.labels
            - path: "annotations"
              fieldRef:
                fieldPath: metadata.annotations
      

