apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: pi
          image: python
          command: ["python","-c", "print('hello')"]
      restartPolicy: Never
  backoffLimit: 4
